name: Ichiroku Eigth Action
on:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app5
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app5
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Test code
        # we assign id so we can refer from other step
        id: ichiroku-test-step
        run: npm run test
      - name: Upload test report
        # let say previous step will fail, and we want to make sure below only run when previous step fail
        # the value after steps is the id we define in previous step
        # without failure() function, below will not trigger as previous step failure will cause next step to stop
        if: failure() && steps.ichiroku-test-step.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: app5/test.json
  build:
    needs: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app5
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Build website
        id: build-website
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: app5/dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
      - name: Output contents
        run: ls
      - name: Deploy
        run: echo "Deploying..."
  # let say we want this jobs to run whenever there is failure job
  report:
    # just by specifying below two jobs, it will still detect if failure happened in job not being specified here
    needs: [lint, deploy]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Ichiroku Output Failure Context
        run: |
          echo "Something went wrong"
          echo "${{ github }}"
    
