name: Ichiroku Sixth Action
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    # define the directory path explicitly
    defaults:
      run:
        working-directory: app3
    steps:
      - name: Ichiroku get code
        uses: actions/checkout@v3
      - name: Ichiroku install dependencies
        run: npm ci
      - name: Ichiroku lint code
        run: npm run lint
      - name: Ichiroku test code
        run: npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app3
    steps:
      - name: Ichiroku get code
        uses: actions/checkout@v3
      - name: Ichiroku install dependencies
        run: npm ci
      - name: Ichiroku build website
        run: npm run build
      - name: Ichiroku show list of files/folders
        run: ls -a
      - name: Ichiroku upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: app3
    steps:
      
      - name: Ichiroku deploy
        run: echo "Deploying..."
